/**
 * enrich-links.mjs
 *
 * Queries the Open Library Search API for every book in books.json and
 * populates `links.openlibrary` (direct work URL) and `links.anna`
 * (ISBN-based Anna's Archive URL) when a confident match is found.
 *
 * Books that aren't matched are written to READING-LIST-LINKS.md as a
 * checklist for manual Goodreads sourcing.
 *
 * Usage:
 *   node scripts/enrich-links.mjs
 *
 * Safe to re-run — skips books that already have links.openlibrary set.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BOOKS_PATH = path.join(__dirname, '../src/lib/books.json');
const CHECKLIST_PATH = path.join(__dirname, '../READING-LIST-LINKS.md');

const DELAY_MS = 350;          // between requests — respectful to OL API
const BATCH_SIZE = 1;          // serial; bump to 3 if you trust the rate limit

// ── helpers ──────────────────────────────────────────────────────────────────

const sleep = ms => new Promise(r => setTimeout(r, ms));

/** Strip everything after ': ' or ' — ' for a cleaner title search */
function shortTitle(title) {
  return title.split(/:\s|—/).shift().trim();
}

/** Take only the first listed author, drop parenthetical roles */
function firstAuthor(author) {
  return author.split(',')[0].replace(/\s*\(.*?\)/, '').trim();
}

/** Normalise a string for loose comparison */
function norm(s) {
  return s.toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' ').trim();
}

/**
 * Returns true if the Open Library result looks like the right book.
 * We check that the OL title starts with (or contains) the start of our title.
 */
function isGoodMatch(book, doc) {
  const ourTitle = norm(shortTitle(book.title));
  const olTitle  = norm(doc.title || '');
  // Accept if the first 15 chars of our title appear in the OL title
  const prefix = ourTitle.substring(0, Math.min(15, ourTitle.length));
  if (!olTitle.includes(prefix)) return false;
  // Year check: allow ±3 years or no year on our side
  if (book.year && doc.first_publish_year) {
    if (Math.abs(book.year - doc.first_publish_year) > 5) return false;
  }
  return true;
}

async function queryOpenLibrary(book) {
  const title  = encodeURIComponent(shortTitle(book.title));
  const author = encodeURIComponent(firstAuthor(book.author));
  const url = `https://openlibrary.org/search.json?title=${title}&author=${author}&limit=1&fields=key,title,first_publish_year,isbn`;

  try {
    const res = await fetch(url, {
      headers: { 'User-Agent': 'cwcorella-reading-list-enrichment/1.0' },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();

    if (!data.docs?.length) return null;
    const doc = data.docs[0];
    if (!isGoodMatch(book, doc)) return null;

    return {
      openlibrary: `https://openlibrary.org${doc.key}`,
      isbn: doc.isbn?.[0] ?? null,
    };
  } catch (err) {
    console.error(`  ✗ fetch error for "${book.title}": ${err.message}`);
    return null;
  }
}

// ── main ─────────────────────────────────────────────────────────────────────

const books = JSON.parse(fs.readFileSync(BOOKS_PATH, 'utf8'));

let found = 0, skipped = 0, missed = 0;
const needsManual = [];

console.log(`Processing ${books.length} books…\n`);

for (let i = 0; i < books.length; i++) {
  const book = books[i];

  // Already enriched — skip
  if (book.links?.openlibrary) {
    skipped++;
    continue;
  }

  process.stdout.write(`[${String(i + 1).padStart(3)}/${books.length}] ${book.title.substring(0, 60)}…`);

  const result = await queryOpenLibrary(book);

  if (result) {
    book.links = book.links ?? {};
    book.links.openlibrary = result.openlibrary;
    if (result.isbn) {
      book.links.anna = `https://annas-archive.org/isbn/${result.isbn}`;
    }
    found++;
    console.log(` ✓ ${result.openlibrary}`);
  } else {
    missed++;
    needsManual.push(book);
    console.log(` — not found`);
  }

  await sleep(DELAY_MS);
}

// Write enriched books.json
fs.writeFileSync(BOOKS_PATH, JSON.stringify(books));
console.log(`\n✓ books.json updated`);
console.log(`  found: ${found}  skipped (already set): ${skipped}  needs manual: ${missed}`);

// ── generate checklist ───────────────────────────────────────────────────────

const checklistLines = [
  '# Reading List — Link Verification Checklist',
  '',
  'Auto-generated by `scripts/enrich-links.mjs`. Re-run after adding manual links to regenerate.',
  '',
  `**Total books:** ${books.length}  `,
  `**Auto-found (Open Library):** ${found + skipped}  `,
  `**Needs manual sourcing:** ${needsManual.length}  `,
  '',
  '---',
  '',
  '## Needs Manual Sourcing',
  '',
  'For each book below: find the correct Goodreads page (or other source), add',
  '`"links": { "goodreads": "URL" }` to the entry in `src/lib/books.json`, then',
  'check the box.',
  '',
  '| # | Done | Title | Author | Year | Category | Notes |',
  '|---|------|-------|--------|------|----------|-------|',
];

needsManual.forEach((b, idx) => {
  const done = '[ ]';
  const title = b.title.replace(/\|/g, '\\|');
  const author = firstAuthor(b.author).replace(/\|/g, '\\|');
  checklistLines.push(
    `| ${idx + 1} | ${done} | ${title} | ${author} | ${b.year ?? '?'} | ${b.category} | |`
  );
});

checklistLines.push('');
checklistLines.push('---');
checklistLines.push('');
checklistLines.push('## All Books — Full Status');
checklistLines.push('');
checklistLines.push('| # | Title | Author | Year | Open Library | Anna\'s Archive | Goodreads | Verified |');
checklistLines.push('|---|-------|--------|------|--------------|----------------|-----------|----------|');

books.forEach((b, idx) => {
  const ol = b.links?.openlibrary ? `[↗](${b.links.openlibrary})` : '—';
  const anna = b.links?.anna ? `[↗](${b.links.anna})` : '—';
  const gr = b.links?.goodreads ? `[↗](${b.links.goodreads})` : '—';
  const verified = b.links?.verified ? '✅' : '[ ]';
  const title = b.title.substring(0, 50).replace(/\|/g, '\\|');
  const author = firstAuthor(b.author).replace(/\|/g, '\\|');
  checklistLines.push(
    `| ${idx + 1} | ${title} | ${author} | ${b.year ?? '?'} | ${ol} | ${anna} | ${gr} | ${verified} |`
  );
});

checklistLines.push('');

fs.writeFileSync(CHECKLIST_PATH, checklistLines.join('\n'));
console.log(`✓ READING-LIST-LINKS.md written (${needsManual.length} books need manual sourcing)`);
