/**
 * enrich-links.mjs
 *
 * Queries the Open Library Search API for every book in books.json and
 * adds Open Library + Anna's Archive links when a confident match is found.
 *
 * Links are stored as [{name, url}] arrays (new open-ended format).
 * Safe to re-run — skips books that already have an Open Library link.
 *
 * Usage:
 *   node scripts/enrich-links.mjs
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BOOKS_PATH = path.join(__dirname, '../src/lib/books.json');
const CHECKLIST_PATH = path.join(__dirname, '../READING-LIST-LINKS.md');

const DELAY_MS = 350;

const sleep = ms => new Promise(r => setTimeout(r, ms));

function shortTitle(title) {
  return title.split(/:\s|—/).shift().trim();
}

function firstAuthor(author) {
  return author.split(',')[0].replace(/\s*\(.*?\)/, '').trim();
}

function norm(s) {
  return s.toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' ').trim();
}

function isGoodMatch(book, doc) {
  const ourTitle = norm(shortTitle(book.title));
  const olTitle  = norm(doc.title || '');
  const prefix = ourTitle.substring(0, Math.min(15, ourTitle.length));
  if (!olTitle.includes(prefix)) return false;
  if (book.year && doc.first_publish_year) {
    if (Math.abs(book.year - doc.first_publish_year) > 5) return false;
  }
  return true;
}

function hasLink(book, name) {
  return book.links?.some(l => l.name === name);
}

async function queryOpenLibrary(book) {
  const title  = encodeURIComponent(shortTitle(book.title));
  const author = encodeURIComponent(firstAuthor(book.author));
  const url = `https://openlibrary.org/search.json?title=${title}&author=${author}&limit=1&fields=key,title,first_publish_year,isbn`;

  try {
    const res = await fetch(url, {
      headers: { 'User-Agent': 'cwcorella-reading-list-enrichment/1.0' },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    if (!data.docs?.length) return null;
    const doc = data.docs[0];
    if (!isGoodMatch(book, doc)) return null;
    return {
      openlibrary: `https://openlibrary.org${doc.key}`,
      isbn: doc.isbn?.[0] ?? null,
    };
  } catch (err) {
    console.error(`  ✗ fetch error for "${book.title}": ${err.message}`);
    return null;
  }
}

// ── main ─────────────────────────────────────────────────────────────────────

const books = JSON.parse(fs.readFileSync(BOOKS_PATH, 'utf8'));

let found = 0, skipped = 0, missed = 0;
const needsManual = [];

console.log(`Processing ${books.length} books…\n`);

for (let i = 0; i < books.length; i++) {
  const book = books[i];

  if (hasLink(book, 'Open Library')) {
    skipped++;
    needsManual.push(book); // track for checklist — already linked but may need others
    continue;
  }

  process.stdout.write(`[${String(i + 1).padStart(3)}/${books.length}] ${book.title.substring(0, 60)}… `);

  const result = await queryOpenLibrary(book);

  if (result) {
    book.links = book.links ?? [];
    book.links.push({ name: 'Open Library', url: result.openlibrary });
    if (result.isbn) {
      book.links.push({ name: "Anna's Archive", url: `https://annas-archive.org/isbn/${result.isbn}` });
    }
    found++;
    console.log(`✓ ${result.openlibrary}`);
  } else {
    missed++;
    needsManual.push(book);
    console.log(`— not found`);
  }

  await sleep(DELAY_MS);
}

fs.writeFileSync(BOOKS_PATH, JSON.stringify(books));
console.log(`\n✓ books.json updated`);
console.log(`  newly found: ${found}  already had OL: ${skipped}  still missing: ${missed}`);

// ── checklist ─────────────────────────────────────────────────────────────────

const stillMissing = books.filter(b => !hasLink(b, 'Open Library'));

const lines = [
  '# Reading List — Link Verification Checklist',
  '',
  'Auto-generated by `scripts/enrich-links.mjs`. Re-run after adding manual links to regenerate.',
  '',
  `**Total books:** ${books.length}  `,
  `**Have Open Library link:** ${books.length - stillMissing.length}  `,
  `**Needs manual sourcing:** ${stillMissing.length}  `,
  '',
  '---',
  '',
  '## Needs Manual Sourcing',
  '',
  '| # | Done | Title | Author | Year | Category |',
  '|---|------|-------|--------|------|----------|',
  ...stillMissing.map((b, idx) =>
    `| ${idx + 1} | [ ] | ${b.title.replace(/\|/g, '\\|')} | ${firstAuthor(b.author).replace(/\|/g, '\\|')} | ${b.year ?? '?'} | ${b.category} |`
  ),
  '',
];

fs.writeFileSync(CHECKLIST_PATH, lines.join('\n'));
console.log(`✓ READING-LIST-LINKS.md written (${stillMissing.length} books still need manual sourcing)`);
